### ISSUE TITLE
Enhancement: lock in/fix certain color choices

### ISSUE THREAD

**Issue by meganrogge** [usernamehw/vscode-theme-generator#1]
It would be awesome if you could, for example, put a check mark icon next to each color choice to "fix" it. This way, you could lock in your choice for one type while shuffling the others.

**Comment by usernamehw** [comment]
Added a lock icon for 7 main colors. Diff and error colors are not randomized, so no lock for them.

![Screenshot (405)](https://user-images.githubusercontent.com/9638156/102678120-625cc680-41b7-11eb-8234-479cd77fcfaa.png)

**Comment by meganrogge** [comment]
Amazing! Thank you so much.
