### ISSUE TITLE
Installed, now what

### ISSUE THREAD

**Issue by gerlinp** [usernamehw/vscode-theme-generator#3]
I'm new to vs code and coding in general. I installed the extension, and have no idea how to start the generator or even where to put these commands. May I please ask for a little more instructions. There is not a lot of instructions on customizing a theme in general just finding one and installing it.

**Comment by Woynert** [comment]
Hi, you can open the editor pressing CTRL + SHIFT + P then writing "Theme Generator"
Hope it help you

**Comment by usernamehw** [comment]
Yes, using "Command Palette" is the easiest way to find what extension does. Names of commands can be found at `Feature Contributions` in extension details:

![Screenshot (451)](https://user-images.githubusercontent.com/9638156/111867041-8d0b1680-8982-11eb-9436-87ae18811725.png)
