### ISSUE TITLE
Question: how to open the theme editor?

### ISSUE THREAD

**Issue by oswcab** [usernamehw/vscode-theme-generator#4]
Installed it and haven't found how to  edit the default themes. Documentation is spare on this. Most probably I'm overlooking something  obvious but have not figured it out yet.

**Comment by usernamehw** [comment]
You can't edit default themes. This extension provides one command: `Theme Generator: Generate a theme`

![Screenshot (463)](https://user-images.githubusercontent.com/9638156/114219812-d47a3680-9973-11eb-9821-3120c2e440b8.png)

Which opens a webview. Its changes are written in the global user settings file.

**Comment by usernamehw** [comment]
If you want to tweak default themes (without using this extension): in `settings.json`:

```js
"workbench.colorCustomizations": {
    "[Default Dark+]": {
        "editor.background": "#ea00ff10",
    },
}
```

**Comment by oswcab** [comment]
That's exactly what I was overlooking. Thanks for your answer!
